"""Nocturne sheet engraver. MIDI is generated by render.py.

    .venv/bin/python render.py nocturne              # MIDI only
    .venv/bin/python pieces/nocturne.py --sheet      # MIDI + PDF score
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from lib.music import load, note_to_midi, notes_to_midi, ql
from render import render
from to_sheet import Sheet


def build_sheet(d, basename="nocturne"):
    melodies = {int(k): v for k, v in d["melodies"].items()}
    score    = d["score"]
    voicings = d["voicings"]
    pattern  = d["lh_arpeggio"]
    dyn_map  = {int(k): v for k, v in d["dynamics"].items()}
    last     = len(score) - 1

    sh = Sheet(d["title"], subtitle=d.get("subtitle"),
               composer=d.get("composer"),
               time_signature=f"{d['time_signature'][0]}/{d['time_signature'][1]}",
               key_sig="e", tempo=("Andante espressivo", d["tempo"]))
    rh, lh = sh.part("treble"), sh.part("bass")

    for i, (chord_name, mel_ref) in enumerate(score):
        if i in dyn_map:
            rh.dyn(dyn_map[i])
        for pitch, dur_ql in melodies[int(mel_ref)]:
            m = note_to_midi(pitch)
            if m is None:
                rh.rest(dur_ql)
            else:
                rh.note(m, dur_ql, fermata=(i == last))
        v   = voicings[chord_name]
        arp = [note_to_midi(v["bass"])] + notes_to_midi(v["upper"])
        if i == last:
            lh.chord(arp, 1.5, fermata=True)
        else:
            for idx in pattern:
                lh.note(arp[idx], 0.5)
    return sh.render(basename)


if __name__ == "__main__":
    if "--sheet" not in sys.argv:
        print("For MIDI only: .venv/bin/python render.py nocturne")
        print("For sheet:     .venv/bin/python pieces/nocturne.py --sheet")
        sys.exit(0)
    d = load("nocturne")
    render("nocturne")   # MIDI first
    build_sheet(d)
    print("engraved output/nocturne.musicxml + output/nocturne.pdf")
